### ISSUE TITLE
Eclipse not able to import "MagicDraw" project

### ISSUE THREAD

**Issue by electrojit** [22ndtech/ndtech-magicdraw-eclipse#1]
First of all thank you very much for sharing this project.
When I tried to follow the video and imported the projects in the Eclipse workspace - I am not able to see the "MagicDraw" project being imported/found.

I suspect that the "MagicDraw" folder does not have the .project, .classpath and .launch files in it.

Is it possible to fix this or provide help on how to fix it?

Thank you

**Comment by jjhegedus** [comment]
Hi @electrojit,
Do you have the MagicDraw application from NoMagic / Dassault licensed and installed?

**Comment by electrojit** [comment]
Sorry for late reply. Yes, I have the license installed. We can close the issue. As I had to stop working on MagicDraw due to project change.

Thank you for your kind support and reply.
